import { getProviderHealth } from "#services/providerHealth";
import type { EndpointName } from "#types/domain";

const descriptions: Record<EndpointName, string> = {
  apiKeyGenerate: "Generates a new client API key and returns it once, along with current issuance totals and optional agent metadata attachments.",
  apiKeyDelete: "Deletes an existing client API key by id and returns the deleted key metadata so admins can revoke access cleanly.",
  requests: "Returns all-time request totals, explicit success/client-error/server-error counters, latency summaries, per-endpoint leaderboards, and provider-level failure breakdowns. Backed by a 5-minute in-memory aggregate cache.",
  volume: "Returns all-time ETH buy and sell volume with a combined total across both directions. Backed by a 5-minute in-memory aggregate cache.",
  adminStats: "Returns the full analytics snapshot with current-day stats, request latency, provider health leaderboards, and all-time request, user, agent, and ETH volume aggregates.",
  stats: "Returns the top-level current-day summary plus explicit success/client-error/server-error request counters, latency summaries, all-time request totals, and ETH volume aggregates.",
  statsRequests: "Returns current-day request totals broken down by success/client-error/server-error, latency, endpoint rates, provider failures, and HTTP status code, plus matching all-time aggregates.",
  statsUsers: "Returns API-key issuance and activity totals, plus per-key and per-agent daily usage, error, and latency rows.",
  statsUser: "Returns filtered single-user API-key analytics by agentId and/or agentWalletEvm, with current-day and all-time request quality and matching key rows.",
  statsAgents: "Returns dashboard-ready per-agent analytics with daily and all-time request quality, latency, and optional per-key rollups.",
  statsVolume: "Returns aggregated native buy and sell volume counters for ETH, Base, BSC, and Solana, plus all-time totals and all-time USD-equivalent volume.",
  approve: "Builds unsigned approval transactions for router, fee-wrapper, or Permit2-based sell flows.",
  holders: "Returns top holder rows for a token, using Moralis on EVM chains and Solana RPC on Solana.",
  walletReview: "Returns wallet profitability, holdings, protocol exposure, approvals, and recent activity for copy-trading analysis.",
  tokenScreener: "Screens tokens across chains using Nansen market, volume, liquidity, and smart-money filters.",
  addressRelatedWallets: "Returns wallets related to an address through transfer and interaction paths to help trace wallet clustering.",
  jupiterDcas: "Returns Solana Jupiter DCA orders for a token so you can inspect automated accumulation behavior.",
  smartMoneyNetflow: "Returns smart-money token accumulation and distribution flows across supported chains.",
  nansenPresets: "Returns named preset request templates for Nansen-backed endpoints so callers can avoid hand-building filters.",
  tokenPoolInfo: "Returns market cap, price, liquidity, holder summary, and 24h movement for a token or pool. Supports fresh=true to bypass provider memoization for debugging.",
  tokenPriceHistory: "Returns normalized price history for a token using an adjustable timeframe.",
  detailedTokenStats: "Returns cached bucketed token stats from Codex for volume, price, liquidity, and trader-count changes across short windows.",
  isScam: "Runs the fast scam triage pass using Honeypot and related contract-security signals.",
  fullAudit: "Builds the deeper risk profile using GoPlus, Honeypot, BubbleMaps, Quick Intel, and chain data.",
  holderAnalysis: "Returns holder concentration, top-wallet breakdowns, and cached distribution context.",
  fudSearch: "Searches social surfaces for scam or exploit concerns tied to a token name, symbol, or address.",
  marketOverview: "Composes chain context, pool info, risk signals, and social data into one response.",
  filterTokens: "Filters tokens across chains by liquidity, volume, market cap, holders, and other on-chain criteria via Codex.",
  filterWallets: "Discovers wallets by realized PnL, win rate, volume, and swap count across configurable time frames via Codex.",
  tokenWallets: "Lists wallets trading a specific token with PnL, balance, and buy/sell stats via Codex.",
  walletStats: "Returns detailed PnL and trading stats for a wallet across 1d/1w/30d/1y time periods via Codex.",
  tokenHolders: "Returns raw holder rows for tokens: Sim by Dune on EVM chains and Solana RPC-derived holder rows on Solana.",
  unwrap: "Builds an unsigned wrapped-native withdraw transaction so a wallet can unwrap WETH/WBNB back into native gas token.",
  swap: "Executes a token swap on the best available DEX route for the specified chain.",
  swapQuote: "Returns a price quote for a swap without executing it.",
  swapDexes: "Lists available DEX routers for a given chain.",
  trendingTokens: "Returns currently trending tokens by social and on-chain momentum.",
  getTopEthTokens: "Returns Ethplorer's top Ethereum tokens sorted by trade volume, market cap, or operation count. Backed by a 10-minute in-memory cache.",
  getNewEthTradableTokens: "Returns Ethplorer's newest tradable Ethereum tokens sorted by creation time. Backed by a 10-minute in-memory cache.",
  newPairs: "Returns recently created trading pairs across supported DEXes.",
  topTraders: "Returns top-performing trader wallets ranked by PnL or win rate.",
  gasFeed: "Returns current gas prices and fee estimates for supported chains.",
  tokenSearch: "Searches for tokens by name, symbol, or address across chains.",
  volatilityScanner: "Scans high-volume tokens for consistent swing patterns, computing support/resistance levels and a composite swing score.",
  priceHistoryIndicators: "Returns OHLCV price history plus timeframe-adaptive technical indicators (RSI, MACD, EMA, Bollinger Bands, ATR, Stoch RSI, Support/Resistance, VWAP, OBV) with an aggregate buy/sell signal.",
  rateMyEntry: "Rates whether a token is a good swing-trade entry right now using price, indicators, volume quality, and scam-risk checks, and suggests a better pullback level when needed.",
};

const cacheHints: Record<EndpointName, number> = {
  apiKeyGenerate: 0,
  apiKeyDelete: 0,
  requests: 300,
  volume: 300,
  adminStats: 0,
  stats: 0,
  statsRequests: 0,
  statsUsers: 0,
  statsUser: 0,
  statsAgents: 0,
  statsVolume: 0,
  approve: 0,
  holders: 120,
  walletReview: 180,
  tokenScreener: 120,
  addressRelatedWallets: 120,
  jupiterDcas: 120,
  smartMoneyNetflow: 120,
  nansenPresets: 0,
  tokenPoolInfo: 60,
  tokenPriceHistory: 120,
  detailedTokenStats: 1800,
  isScam: 120,
  fullAudit: 900,
  holderAnalysis: 21600,
  fudSearch: 180,
  marketOverview: 120,
  filterTokens: 300,
  filterWallets: 1800,
  tokenWallets: 180,
  walletStats: 180,
  tokenHolders: 120,
  unwrap: 0,
  swap: 0,
  swapQuote: 0,
  swapDexes: 3600,
  trendingTokens: 120,
  getTopEthTokens: 600,
  getNewEthTradableTokens: 600,
  newPairs: 60,
  topTraders: 300,
  gasFeed: 0,
  tokenSearch: 60,
  volatilityScanner: 300,
  priceHistoryIndicators: 60,
  rateMyEntry: 60,
};

export function buildEndpointScaffold(endpoint: EndpointName, request: Record<string, unknown>) {
  return {
    endpoint,
    status: "scaffold",
    description: descriptions[endpoint],
    request,
    recommendedCacheSeconds: cacheHints[endpoint],
    providers: getProviderHealth(endpoint),
    nextImplementationTargets: [
      "Replace scaffold data with normalized provider adapters.",
      "Cache expensive sources like BubbleMaps and holder snapshots.",
      "Add chain-aware routing so the same endpoint can fan out by network."
    ]
  };
}