import { getProviderHealth } from "#services/providerHealth";
import type { EndpointName } from "#types/domain";

const descriptions: Record<EndpointName, string> = {
  apiKeyGenerate: "Generates a new client API key and returns it once, along with current issuance totals.",
  adminStats: "Returns the full daily analytics snapshot, including requests, users, and ETH volume counters.",
  stats: "Returns the top-level daily summary: requests, API-key users, and ETH volume.",
  statsRequests: "Returns daily request totals broken down by endpoint and HTTP status code.",
  statsUsers: "Returns API-key issuance and activity totals, plus per-key daily usage rows.",
  statsVolume: "Returns aggregated ETH buy and sell volume counters for the current UTC day.",
  approve: "Builds unsigned approval transactions for router, fee-wrapper, or Permit2-based sell flows.",
  holders: "Returns top holder rows for a token, using Moralis on EVM chains and Solana RPC on Solana.",
  walletReview: "Returns wallet profitability, holdings, protocol exposure, approvals, and recent activity for copy-trading analysis.",
  tokenPoolInfo: "Returns market cap, price, liquidity, holder summary, and 24h movement for a token or pool.",
  tokenPriceHistory: "Returns normalized price history for a token using an adjustable timeframe.",
  detailedTokenStats: "Returns cached bucketed token stats from Codex for volume, price, liquidity, and trader-count changes across short windows.",
  isScam: "Runs the fast scam triage pass using Honeypot and related contract-security signals.",
  fullAudit: "Builds the deeper risk profile using GoPlus, Honeypot, BubbleMaps, Quick Intel, and chain data.",
  holderAnalysis: "Returns holder concentration, top-wallet breakdowns, and cached distribution context.",
  fudSearch: "Searches social surfaces for scam or exploit concerns tied to a token name, symbol, or address.",
  marketOverview: "Composes chain context, pool info, risk signals, and social data into one response.",
  filterTokens: "Filters tokens across chains by liquidity, volume, market cap, holders, and other on-chain criteria via Codex.",
  filterWallets: "Discovers wallets by realized PnL, win rate, volume, and swap count across configurable time frames via Codex.",
  tokenWallets: "Lists wallets trading a specific token with PnL, balance, and buy/sell stats via Codex.",
  walletStats: "Returns detailed PnL and trading stats for a wallet across 1d/1w/30d/1y time periods via Codex.",
  tokenHolders: "Returns raw holder rows for tokens: Sim by Dune on EVM chains and Solana RPC-derived holder rows on Solana.",
  unwrap: "Builds an unsigned wrapped-native withdraw transaction so a wallet can unwrap WETH/WBNB back into native gas token.",
  swap: "Executes a token swap on the best available DEX route for the specified chain.",
  swapQuote: "Returns a price quote for a swap without executing it.",
  swapDexes: "Lists available DEX routers for a given chain.",
  trendingTokens: "Returns currently trending tokens by social and on-chain momentum.",
  newPairs: "Returns recently created trading pairs across supported DEXes.",
  topTraders: "Returns top-performing trader wallets ranked by PnL or win rate.",
  gasFeed: "Returns current gas prices and fee estimates for supported chains.",
  tokenSearch: "Searches for tokens by name, symbol, or address across chains.",
  volatilityScanner: "Scans high-volume tokens for consistent swing patterns, computing support/resistance levels and a composite swing score.",
  priceHistoryIndicators: "Returns OHLCV price history plus timeframe-adaptive technical indicators (RSI, MACD, EMA, Bollinger Bands, ATR, Stoch RSI, Support/Resistance, VWAP, OBV) with an aggregate buy/sell signal.",
};

const cacheHints: Record<EndpointName, number> = {
  apiKeyGenerate: 0,
  adminStats: 0,
  stats: 0,
  statsRequests: 0,
  statsUsers: 0,
  statsVolume: 0,
  approve: 0,
  holders: 120,
  walletReview: 180,
  tokenPoolInfo: 60,
  tokenPriceHistory: 120,
  detailedTokenStats: 1800,
  isScam: 120,
  fullAudit: 900,
  holderAnalysis: 21600,
  fudSearch: 180,
  marketOverview: 120,
  filterTokens: 300,
  filterWallets: 1800,
  tokenWallets: 180,
  walletStats: 180,
  tokenHolders: 120,
  unwrap: 0,
  swap: 0,
  swapQuote: 0,
  swapDexes: 3600,
  trendingTokens: 120,
  newPairs: 60,
  topTraders: 300,
  gasFeed: 0,
  tokenSearch: 60,
  volatilityScanner: 300,
  priceHistoryIndicators: 60,
};

export function buildEndpointScaffold(endpoint: EndpointName, request: Record<string, unknown>) {
  return {
    endpoint,
    status: "scaffold",
    description: descriptions[endpoint],
    request,
    recommendedCacheSeconds: cacheHints[endpoint],
    providers: getProviderHealth(endpoint),
    nextImplementationTargets: [
      "Replace scaffold data with normalized provider adapters.",
      "Cache expensive sources like BubbleMaps and holder snapshots.",
      "Add chain-aware routing so the same endpoint can fan out by network."
    ]
  };
}