import type { ProviderRecord } from "#types/domain";

export const providerRegistry: ProviderRecord[] = [
  { id: "arkham", label: "Arkham", category: "walletTracking", folder: "Alpha_Wallet_tracking/Arkham", env: ["ARKHAM_API_KEY"], endpoints: ["walletReview", "holderAnalysis", "marketOverview"] },
  { id: "debank", label: "DeBank", category: "walletTracking", folder: "Alpha_Wallet_tracking/Debank", env: ["DEBANK_API_KEY"], endpoints: ["walletReview", "holderAnalysis", "marketOverview"] },
  { id: "moralis", label: "Moralis", category: "walletTracking", folder: "Alpha_Wallet_tracking/Moralis", env: ["MORALIS_API_KEY"], endpoints: ["walletReview", "holderAnalysis", "marketOverview"] },
  { id: "nansen", label: "Nansen", category: "walletTracking", folder: "Alpha_Wallet_tracking/Nansen", env: ["NANSEN_API_KEY"], endpoints: ["walletReview", "holderAnalysis", "marketOverview"] },
  { id: "aerodromeV2", label: "Aerodrome V2", category: "dex", folder: "DEX/Chain/BASE/AERODOME_V2", env: [], endpoints: ["tokenPoolInfo", "marketOverview"] },
  { id: "baseGasFeed", label: "Base Gas Feed", category: "chainInfra", folder: "DEX/Chain/BASE/GAS_FEED", env: ["BASESCAN_API_KEY"], endpoints: ["marketOverview"] },
  { id: "baseRpc", label: "Base RPC", category: "chainInfra", folder: "DEX/Chain/BASE/RPC", env: ["BASE_RPC_URL"], endpoints: ["tokenPoolInfo", "holderAnalysis", "marketOverview"] },
  { id: "baseUniswapV2", label: "Base Uniswap V2", category: "dex", folder: "DEX/Chain/BASE/UNISWAP_V2", env: [], endpoints: ["tokenPoolInfo", "marketOverview"] },
  { id: "baseUniswapV3", label: "Base Uniswap V3", category: "dex", folder: "DEX/Chain/BASE/UNISWAP_V3", env: [], endpoints: ["tokenPoolInfo", "marketOverview"] },
  { id: "baseUniswapV4", label: "Base Uniswap V4", category: "dex", folder: "DEX/Chain/BASE/UNISWAP_V4", env: [], endpoints: ["tokenPoolInfo", "marketOverview"] },
  { id: "bscGasFeed", label: "BSC Gas Feed", category: "chainInfra", folder: "DEX/Chain/BSC/GAS_FEED", env: ["BSCSCAN_API_KEY"], endpoints: ["marketOverview"] },
  { id: "pancakeV2", label: "PancakeSwap V2", category: "dex", folder: "DEX/Chain/BSC/PANCAKESWAP_V2", env: [], endpoints: ["tokenPoolInfo", "marketOverview"] },
  { id: "pancakeV3", label: "PancakeSwap V3", category: "dex", folder: "DEX/Chain/BSC/PANCAKESWAP_V3", env: [], endpoints: ["tokenPoolInfo", "marketOverview"] },
  { id: "bscRpc", label: "BSC RPC", category: "chainInfra", folder: "DEX/Chain/BSC/RPC", env: ["BSC_RPC_URL"], endpoints: ["tokenPoolInfo", "holderAnalysis", "marketOverview"] },
  { id: "ethGasFeed", label: "Ethereum Gas Feed", category: "chainInfra", folder: "DEX/Chain/ETH/GAS_FEED", env: ["ETHERSCAN_API_KEY"], endpoints: ["marketOverview"] },
  { id: "ethRpc", label: "Ethereum RPC", category: "chainInfra", folder: "DEX/Chain/ETH/RPC", env: ["ETH_RPC_URL"], endpoints: ["tokenPoolInfo", "holderAnalysis", "marketOverview"] },
  { id: "ethUniswapV2", label: "Ethereum Uniswap V2", category: "dex", folder: "DEX/Chain/ETH/UNISWAP_V2", env: [], endpoints: ["tokenPoolInfo", "marketOverview"] },
  { id: "ethUniswapV3", label: "Ethereum Uniswap V3", category: "dex", folder: "DEX/Chain/ETH/UNISWAP_V3", env: [], endpoints: ["tokenPoolInfo", "marketOverview"] },
  { id: "ethUniswapV4", label: "Ethereum Uniswap V4", category: "dex", folder: "DEX/Chain/ETH/UNISWAP_V4", env: [], endpoints: ["tokenPoolInfo", "marketOverview"] },
  { id: "solGasFeed", label: "Solana Gas Feed", category: "chainInfra", folder: "DEX/Chain/SOL/GAS_FEED", env: [], endpoints: ["marketOverview"] },
  { id: "meteora", label: "Meteora", category: "dex", folder: "DEX/Chain/SOL/METEORA", env: [], endpoints: ["tokenPoolInfo", "marketOverview"] },
  { id: "pumpdex", label: "PumpDex", category: "dex", folder: "DEX/Chain/SOL/PUMPDEX", env: [], endpoints: ["tokenPoolInfo", "marketOverview"] },
  { id: "raydium", label: "Raydium", category: "dex", folder: "DEX/Chain/SOL/RADYUM", env: [], endpoints: ["tokenPoolInfo", "marketOverview"] },
  { id: "solRpc", label: "Solana RPC", category: "chainInfra", folder: "DEX/Chain/SOL/RPC", env: ["SOL_RPC_URL"], endpoints: ["tokenPoolInfo", "holderAnalysis", "marketOverview"] },
  { id: "defiLlama", label: "DefiLlama", category: "marketData", folder: "Market_data/DeFi/DefiLlama", env: [], endpoints: ["marketOverview"] },
  { id: "dune", label: "Dune Analytics", category: "marketData", folder: "Market_data/DeFi/DuneAnalytics", env: ["DUNE_API_KEY", "DUNE_QUERY_ID"], endpoints: ["holderAnalysis", "marketOverview"] },
  { id: "birdeye", label: "Birdeye", category: "marketData", folder: "Market_data/LowCaps/Birdeye", env: ["BIRDEYE_API_KEY"], endpoints: ["tokenPoolInfo", "tokenPriceHistory", "holderAnalysis", "marketOverview"] },
  { id: "dexScreener", label: "DEX Screener", category: "marketData", folder: "Market_data/LowCaps/DEX_Screener", env: [], endpoints: ["tokenPoolInfo", "tokenPriceHistory", "marketOverview"] },
  { id: "dextools", label: "DEXTools", category: "marketData", folder: "Market_data/LowCaps/Dextoools", env: ["DEXTOOLS_API_KEY"], endpoints: ["tokenPoolInfo", "marketOverview"] },
  { id: "geckoTerminal", label: "GeckoTerminal", category: "marketData", folder: "Market_data/LowCaps/GeckoTerminal", env: [], endpoints: ["tokenPoolInfo", "tokenPriceHistory", "marketOverview"] },
  { id: "alchemy", label: "Alchemy", category: "marketData", folder: "Market_data/MidCapsAndMajors/Alchemy", env: ["ALCHEMY_API_KEY"], endpoints: ["tokenPriceHistory"] },
  { id: "coinGecko", label: "CoinGecko", category: "marketData", folder: "Market_data/MidCapsAndMajors/CoinGecko", env: ["COINGECKO_PRO_API_KEY"], endpoints: ["tokenPoolInfo", "tokenPriceHistory", "marketOverview"] },
  { id: "coinMarketCap", label: "CoinMarketCap", category: "marketData", folder: "Market_data/MidCapsAndMajors/Coinmarketcap", env: ["CMC_API_KEY"], endpoints: ["tokenPoolInfo", "marketOverview"] },
  { id: "newPairsDexScreener", label: "DexScreener New Pairs", category: "newPairs", folder: "New_pairs/Dexscreener_new_pairs", env: [], endpoints: ["marketOverview"] },
  { id: "pumpFun", label: "Pump.fun Feed", category: "newPairs", folder: "New_pairs/Pump_fun_feed", env: [], endpoints: ["marketOverview"] },
  { id: "raydiumNewPools", label: "Raydium New Pool Events", category: "newPairs", folder: "New_pairs/Raydium_new_pool_events", env: [], endpoints: ["marketOverview"] },
  { id: "uniswapPairCreation", label: "Uniswap Pair Creation Events", category: "newPairs", folder: "New_pairs/Uniswap_pair_creation_events", env: [], endpoints: ["marketOverview"] },
  { id: "bubbleMaps", label: "BubbleMaps", category: "risk", folder: "Risk/Bubblemaps", env: ["BUBBLEMAPS_API_KEY"], endpoints: ["fullAudit", "holderAnalysis", "marketOverview"] },
  { id: "goPlus", label: "GoPlus", category: "risk", folder: "Risk/GoPlus", env: [], endpoints: ["isScam", "fullAudit", "marketOverview"] },
  { id: "honeypot", label: "Honeypot.is", category: "risk", folder: "Risk/Honeypot_is", env: [], endpoints: ["isScam", "fullAudit", "marketOverview"] },
  { id: "quickIntel", label: "Quick Intel", category: "risk", folder: "Risk/Quick_Intel", env: ["QUICKINTEL_API_KEY"], endpoints: ["fullAudit", "marketOverview"] },
  { id: "telegramChannel", label: "Telegram Channel", category: "sentiment", folder: "Sentiment/LowCaps/Telegram_groups/Channel", env: ["TELEGRAM_BOT_TOKEN"], endpoints: ["fudSearch", "marketOverview"] },
  { id: "telegramListingAlert", label: "Telegram Listing Alert", category: "sentiment", folder: "Sentiment/LowCaps/Telegram_groups/ListingAlert", env: ["TELEGRAM_BOT_TOKEN"], endpoints: ["fudSearch", "marketOverview"] },
  { id: "xCaAnalysis", label: "X CA Analysis", category: "sentiment", folder: "Sentiment/LowCaps/X/Ca_Analysis", env: ["X_BEARER_TOKEN"], endpoints: ["fudSearch", "marketOverview"] },
  { id: "xKol", label: "X KOL", category: "sentiment", folder: "Sentiment/LowCaps/X/KOL", env: ["X_BEARER_TOKEN"], endpoints: ["fudSearch", "marketOverview"] },
  { id: "xProjectAccount", label: "X Project Account Analysis", category: "sentiment", folder: "Sentiment/LowCaps/X/ProjectAccountAnalysis", env: ["X_BEARER_TOKEN"], endpoints: ["fudSearch", "marketOverview"] },
  { id: "lunarCrush", label: "LunarCrush", category: "sentiment", folder: "Sentiment/Majors/LunarCrush", env: ["LUNARCRUSH_API_KEY"], endpoints: ["fudSearch", "marketOverview"] },
  { id: "polymarket", label: "Polymarket", category: "sentiment", folder: "Sentiment/Majors/Polymarket", env: [], endpoints: ["marketOverview"] },
  { id: "reddit", label: "Reddit API", category: "sentiment", folder: "Sentiment/Majors/Reddit_API", env: ["REDDIT_CLIENT_ID", "REDDIT_CLIENT_SECRET", "REDDIT_USER_AGENT"], endpoints: ["fudSearch", "marketOverview"] },
  { id: "santiment", label: "Santiment", category: "sentiment", folder: "Sentiment/Majors/Santiment", env: ["SANTIMENT_API_KEY"], endpoints: ["fudSearch", "marketOverview"] }
];