export type EndpointName =
  | "apiKeyGenerate"
  | "apiKeyDelete"
  | "requests"
  | "volume"
  | "adminStats"
  | "stats"
  | "statsRequests"
  | "statsUsers"
  | "statsUser"
  | "statsAgents"
  | "statsVolume"
  | "approve"
  | "holders"
  | "walletReview"
  | "tokenPoolInfo"
  | "tokenPriceHistory"
  | "detailedTokenStats"
  | "isScam"
  | "fullAudit"
  | "holderAnalysis"
  | "fudSearch"
  | "marketOverview"
  | "filterTokens"
  | "filterWallets"
  | "tokenWallets"
  | "walletStats"
  | "tokenHolders"
  | "unwrap"
  | "swap"
  | "swapQuote"
  | "swapDexes"
  | "trendingTokens"
  | "getTopEthTokens"
  | "newPairs"
  | "topTraders"
  | "gasFeed"
  | "tokenSearch"
  | "volatilityScanner"
  | "priceHistoryIndicators";

export type ProviderRecord = {
  id: string;
  label: string;
  category: string;
  folder: string;
  env: string[];
  endpoints: EndpointName[];
};